parse_config:

  raw_binding_map:
    LT(NAV, KC_SPC):
      tap: SPACE
      hold: misc
    LT(SYMBOLS, KC_ENT):
      tap: ENTER
      hold: symbols
    TD(ADAPTIVE_BSPC):
      tap: BSPC
      hold: adaptive
